# DanceMotionAI Configuration

# General settings
general:
  seed: 42
  num_workers: 4
  device: 'cuda'  # 'cuda' or 'cpu'
  debug: false

# Input/output settings
io:
  input_size: [512, 512]  # Height, Width
  fps: 30
  max_sequence_length: 1800  # Maximum number of frames (60 seconds at 30 fps)

# 3D Pose Estimation settings
pose_estimation:
  model_type: 'dancehrnet'
  pretrained_weights: 'weights/dancehrnet_weights.pth'
  num_joints: 25
  num_layers: 6
  hidden_dim: 512
  num_heads: 8
  dropout: 0.1
  agt_blocks: 4  # Number of Adaptive Graph Transformer blocks
  graph_layers: 3  # Number of GCN layers
  graph_hidden_dim: 256
  confidence_threshold: 0.5  # Minimum confidence for keypoints

# 4DHands settings
hands_4d:
  model_type: 'rat_sir'  # RAT-SIR architecture
  pretrained_weights: 'weights/hands_4d_weights.pth'
  num_hand_joints: 21  # Per hand
  hidden_dim: 256
  num_layers: 4
  dropout: 0.1
  rat_blocks: 3  # Number of Relation-aware Tokenization blocks
  sir_blocks: 2  # Number of Spatio-temporal Interaction Reasoning blocks
  confidence_threshold: 0.4

# Multimodal Analysis settings
multimodal_analysis:
  model_type: 'danceformer'
  pretrained_weights: 'weights/danceformer_weights.pth'
  hidden_dim: 512
  num_layers: 6
  num_heads: 8
  dropout: 0.1
  cross_modal_heads: 4  # Number of cross-modal attention heads
  temporal_window: 64  # Number of frames to consider for temporal analysis
  music_feature_dim: 128
  pose_feature_dim: 256
  output_feature_dim: 512

# Music Analysis settings
music_analysis:
  hop_length: 512
  n_fft: 2048
  n_mels: 128
  sample_rate: 22050
  beat_frames_tolerance: 2  # Frames tolerance for beat detection
  feature_rate: 30  # Features per second (should match video fps)
  feature_types:
    - 'mfcc'  # Mel-frequency cepstral coefficients
    - 'chroma'  # Chromagram
    - 'onset'  # Onset strength
    - 'tempo'  # Tempo features
    - 'beat'  # Beat tracking

# Similarity Analysis settings
similarity_analysis:
  model_type: 'dance_dtw'
  pretrained_weights: 'weights/dance_dtw_weights.pth'
  feature_dim: 512
  num_layers: 4
  hidden_dim: 256
  dropout: 0.1
  dtw_window: 0.1  # DTW window size as fraction of sequence length
  similarity_threshold: 0.8  # Threshold for similarity detection
  wavelet_levels: 5  # Number of wavelet decomposition levels
  distance_weights:
    position: 0.4
    velocity: 0.2
    acceleration: 0.1
    angle: 0.3

# Visualization settings
visualization:
  skeleton_color: [0, 255, 0]  # RGB
  joint_color: [255, 0, 0]  # RGB
  skeleton_thickness: 3
  joint_radius: 5
  hand_color: [0, 0, 255]  # RGB
  hand_skeleton_thickness: 2
  hand_joint_radius: 3
  background_color: [0, 0, 0]  # RGB
  text_color: [255, 255, 255]  # RGB
  font_scale: 0.7
  include_confidence: true  # Show confidence scores
  include_frame_number: true  # Show frame numbers
  include_metrics: true  # Show metrics during visualization
  side_by_side: true  # Side-by-side comparison in comparison mode
  diff_highlight_color: [255, 255, 0]  # Color to highlight differences
  diff_threshold: 0.2  # Threshold for highlighting differences
